kind: Secret
apiVersion: v1
metadata:
  name: gh-credentials
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
data:
  # GITHUB_TOKEN: {{ .Values.backstage.github.pat }}
  AUTH_GITHUB_APP_ID: {{ .Values.backstage.github.appId | b64enc }}
  AUTH_GITHUB_CLIENT_ID: {{ .Values.backstage.github.clientId | b64enc}}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.backstage.github.clientSecret | b64enc}}
  AUTH_GITHUB_PRIVATE_KEY: {{ .Values.backstage.github.privateKey | b64enc }}
type: Opaque
