kind: Secret
apiVersion: v1
metadata:
  name: techdocs-s3-variables
  labels:
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  BUCKET_NAME: {{ .Values.backstage.techdocs.bucketName }}
  AWS_ACCESS_KEY_ID: {{ .Values.backstage.techdocs.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backstage.techdocs.secretAccessKey }}
  # BUCKET_HOST: {{ .Values.backstage.techdocs.bucketName }}
  REGION: {{ .Values.backstage.techdocs.region }}
type: Opaque
