kind: Secret
apiVersion: v1
metadata:
  name: gh-credentials
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  # GITHUB_TOKEN: {{ .Values.backstage.github.pat }}
  AUTH_GITHUB_APP_ID: {{ .Values.backstage.github.appId }}
  AUTH_GITHUB_CLIENT_ID: {{ .Values.backstage.github.clientId }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.backstage.github.clientSecret }}
type: Opaque
