kind: Secret
apiVersion: v1
metadata:
  name: quay-token
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  QUAY_TOKEN: {{ .Values.backstage.quay.token }}
type: Opaque
