---

- name: Set facts
  ansible.builtin.set_fact:
    _backstage_redirect_url: "https://backstage-{{ ocp4_workload_platform_engineering_workshop_rhdh_namespace }}.{{ r_openshift_subdomain }}/api/auth/oidc/handler/frame" # yamllint disable-line rule:line-length
    _backstage_web_origin: "https://backstage-{{ ocp4_workload_platform_engineering_workshop_rhdh_namespace }}.{{ r_openshift_subdomain }}" # yamllint disable-line rule:line-length

- name: Debug
  ansible.builtin.debug:
    msg: "Keycloak Backstage Realm Client Secret {{ocp4_workload_platform_engineering_workshop_rhbk_client_backstage_secret}}"

- name: Create RHBK application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'keycloak/keycloak-application.yaml.j2') | from_yaml }}"
