---

- name: Install OpenShift Pipelines operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: openshift-pipelines-operator-rh
    install_operator_namespace: openshift-operators
    install_operator_channel: latest
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: true
    install_operator_starting_csv: ""
    install_operator_catalogsource_setup: false
    install_operator_catalogsource_name: ""
    install_operator_catalogsource_namespace: openshift-marketplace
    install_operator_catalogsource_image: ""
    install_operator_catalogsource_image_tag: ""
