---

- name: Install Orchestrator operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: orchestrator-operator
    install_operator_namespace: orchestrator
    install_operator_catalogsource_setup: true
    # install_operator_channel: "{{ ocp4_workload_platform_engineering_workshop_openshift_gitops_operator_channel }}"
    # install_operator_catalog: "{{ ocp4_workload_platform_engineering_workshop_openshift_gitops_operator_catalog }}"
    install_operator_automatic_install_plan_approval: true
    # install_operator_starting_csv: "{{ ocp4_workload_platform_engineering_workshop_openshift_gitops_operator_starting_csv }}"
    install_operator_catalogsource_name: orchestrator-operator
    install_operator_packagemanifest_name: orchestrator-operator
    install_operator_catalogsource_namespace: openshift-marketplace
    install_operator_catalogsource_image: quay.io/orchestrator/orchestrator-operator-catalog
    install_operator_catalogsource_image_tag: v1.2.0

- name: "Deploy Orchestrator CR"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'orchestrator/orchestrator.yaml.j2') }}"
  retries: 10
  delay: 30
