---
- name: "Create user namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'parasol/namespace.yaml.j2') }}"
  vars:
    r_platform_engineering_workshop_namespaces:
      - name: parasol
        managedByArgo: ""
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'parasol/rolebinding.yaml.j2') }}"
  vars:
    r_platform_engineering_workshop_bindings:
      - namespace: parasol
        role: "admin"
  retries: 10
  delay: 30


- name: Create parasol keycloak realm
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'parasol/keycloak-realm-application.yaml.j2') | from_yaml }}"


- name: Deploy Parasol application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'parasol/parasol-application.yaml.j2') }}"
