---
# Implement your Post Workload deployment tasks here
# --------------------------------------------------

- name: Wait for the keycloak-initial-admin secret to be available
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: keycloak
    name: keycloak-initial-admin
  register: secret_data
  until: secret_data.resources | length > 0  # Wait until the secret is found
  retries: 100
  delay: 10
  failed_when: secret_data.resources | length == 0
  ignore_errors: false

- name: Print Keycloak admin username and password
  debug:
    msg: "Keycloak login: {{ secret_data.resources[0].data.username | b64decode }} / {{ secret_data.resources[0].data.password | b64decode }}"

# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Workload tasks completed successfully."
  when:
    - not silent | bool
    - not workload_shared_deployment | default(false) | bool

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Software checks completed successfully"
  when:
    - not silent | bool
    - workload_shared_deployment | default(false) | bool
