---
# Implement your Post Workload deployment tasks here
# --------------------------------------------------

- name: Get keycloak-initial-admin secret data
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: keycloak-initial-admin
    namespace: keycloak  # Replace with the namespace
  register: secret_data

- name: Print Keycloak admin username and password
  debug:
    msg: "Keycloak login: {{ secret_data.resources[0].data.username | b64decode }} / {{ secret_data.resources[0].data.password | b64decode }}"

# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Workload tasks completed successfully."
  when:
    - not silent | bool
    - not workload_shared_deployment | default(false) | bool

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Software checks completed successfully"
  when:
    - not silent | bool
    - workload_shared_deployment | default(false) | bool
