---
- name: Get Argo CD admin password from secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: openshift-gitops-cluster
    namespace: openshift-gitops
  register: secret_data

- name: Set Argo CD admin password fact
  set_fact:
    argocd_admin_password: "{{ secret_data.resources[0].data['admin.password'] | b64decode }}"

- name: Install RHDH Application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'developer-hub/developer-hub-application.yaml.j2') }}"
