---

- name: Install Orchestrator
  ansible.builtin.include_tasks: orchestrator.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Install RHBK
  ansible.builtin.include_tasks: keycloak.yml

- name: Install Red Hat Developer Hub
  ansible.builtin.include_tasks: redhat_developer_hub.yml

- name: Deploy Parasol Application
  ansible.builtin.include_tasks: parasol.yml

- name: Print Common Password
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
    - ""
    - "password: {{ common_password }}"
